{{- if and .Values.serveBatch.enabled .Values.serveBatch.apiKey (not .Values.serveBatch.existingApiKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forge.fullname" . }}-api-key
  labels: {{- include "forge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.serveBatch.existingApiKeySecretKey }}: {{ .Values.serveBatch.apiKey | quote }}
{{- end }}
